apiVersion: v1
kind: Service
metadata:
  name: express-web-app
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: express-web-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
