apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-t2s
  namespace: apps
  labels:
    app: express-t2s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-t2s
  template:
    metadata:
      labels:
        app: express-t2s
    spec:
      containers:
        - name: app
          image: "<ECR-ACCOUNT-ID>.dkr.ecr.<REGION>.amazonaws.com/express-t2s:latest" # << replace
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: NODE_ENV
              value: "production"
